apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: api:latest
        livenessProbe:
          httpGet: &id001
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        name: api
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet: *id001
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
